#!/bin/bash

SCRIPTS_FOLDER=`pwd`

function install_help() {
	echo "install helper script"
	echo "Usage:"
	echo "./install.sh go"
	echo "	install golang"
	echo "./install.sh vim"
	echo "	install vim mercurial git meld"
	echo "./install.sh git"
	echo "	install git and git lfs support"
	echo "./install.sh qt"
	echo "	install qt (raspbian only)"
	echo "./install.sh adb"
	echo "	install adb (raspbian only)"
	echo "./install.sh nvidia"
	echo "	install nvidia drivers and cuda toolkit"
	echo "./install.sh openscad"
	echo "	compile and install openscad"
	echo "./install.sh fritzing"
	echo "	compile and install fritzing"
}

function install_git() {
	read -p "We need root permissions to proceed. Press any key to continue"

	sudo bash ./install_scripts/install_git_lfs.sh
}

function install_go() {
	bash ./install_scripts/install_golang_source.sh

	read -p "We need root permissions to proceed. Press any key to continue"

	sudo bash ./install_scripts/install_golang.sh
}

function install_openscad() {
	bash ./compile_scripts/compile_openscad.sh
}

function install_fritzing() {
	bash ./compile_scripts/compile_fritzing.sh
}


COMMAND="$1"

case "$1" in
	go) shift;		install_go ;;
	vim) shift;		install_vim ;;
	git) shift;		install_git ;;
	qt) shift;		install_qt ;;
	adb) shift;		install_adb ;;
	nvidia) shift;		install_nvidia ;;
	openscad) shift;	install_openscad ;;
	fritzing) shift;	install_fritzing ;;
	*)		install_help ;;
esac

exit 0

