#!/bin/bash

SCRIPTS_FOLDER=$( dirname "${BASH_SOURCE[0]}" )

function install_help() {
	echo "install helper script"
	echo "Usage:"
	echo "./install.sh go"
	echo "	install golang"
	echo "./install.sh java"
	echo "	install java"
	echo "./install.sh vim"
	echo "	install vim mercurial git meld"
	echo "./install.sh git"
	echo "	install git and git lfs support"
	echo "./install.sh qt"
	echo "	install qt (raspbian only)"
	echo "./install.sh adb"
	echo "	install adb (raspbian only)"
	echo "./install.sh nvidia"
	echo "	install nvidia drivers and cuda toolkit"
	echo "./install.sh openscad"
	echo "	compile and install openscad"
	echo "./install.sh fritzing"
	echo "	compile and install fritzing"
	echo "./install.sh opencv"
	echo "	compile and install opencv 4"
	echo "./install.sh wordpress"
	echo "	install wordpress in folder wp"
	echo "./install.sh rpitools"
	echo "	install raspberry pi development tools"
}

function install_rpitools() {
	read -p "We need root permissions to proceed. Press any key to continue"

	sudo apt update
	sudo apt install gcc-multilib lib32z1 lib32ncurses5


	bash $SCRIPTS_FOLDER/install_scripts/install_rpitools.sh
}


function install_git() {
	read -p "We need root permissions to proceed. Press any key to continue"

	sudo bash $SCRIPTS_FOLDER/install_scripts/install_git_lfs.sh
}

function install_java() {
	read -p "We need root permissions to proceed. Press any key to continue"

	sudo bash $SCRIPTS_FOLDER/install_scripts/install_java.sh
}


function install_go() {
	bash $SCRIPTS_FOLDER/install_scripts/install_golang_source.sh

	read -p "We need root permissions to proceed. Press any key to continue"

	sudo bash ./install_scripts/install_golang.sh
}

function install_wordpress() {
	bash $SCRIPTS_FOLDER/install_scripts/install_wordpress.sh
}

function install_openscad() {
	bash $SCRIPTS_FOLDER/compile_scripts/compile_openscad.sh
}

function install_fritzing() {
	bash $SCRIPTS_FOLDER/compile_scripts/compile_fritzing.sh
}

function install_opencv() {
	bash $SCRIPTS_FOLDER/compile_scripts/compile_opencv.sh
}


COMMAND="$1"

case "$1" in
	go) shift;		install_go ;;
	vim) shift;		install_vim ;;
	java) shift;		install_java ;;
	git) shift;		install_git ;;
	qt) shift;		install_qt ;;
	adb) shift;		install_adb ;;
	nvidia) shift;		install_nvidia ;;
	openscad) shift;	install_openscad ;;
	fritzing) shift;	install_fritzing ;;
	opencv) shift;		install_opencv ;;
	wordpress) shift;	install_wordpress ;;
	rpitools) shift;	install_rpitools ;;
	*)			install_help ;;
esac

exit 0

